# Generated by Django 5.1.1 on 2024-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='static/image/')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=200)),
                ('quest1', models.CharField(max_length=40)),
                ('quest2', models.CharField(max_length=40)),
                ('quest3', models.CharField(max_length=40)),
                ('starRating', models.BooleanField(default=True)),
            ],
        ),
    ]
