# Generated by Django 5.1.1 on 2024-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacedata',
            name='quest1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='spacedata',
            name='quest2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='spacedata',
            name='quest3',
            field=models.CharField(max_length=80),
        ),
    ]
